FROM mcr.microsoft.com/dotnet/sdk:10.0-resolute-amd64 AS builder

COPY "2_total.cs" .

RUN dotnet publish "2_total.cs" \
    -r linux-x64 \
    -c Release \
    --self-contained true \
    -p:DebugSymbols=false \
    -p:DebugType=None \
    -p:PublishAot=false \
    -p:PublishSingleFile=true \
    -o publish

FROM ubuntu:26.04 AS final
# OR
#FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-resolute-amd64 AS final

LABEL \
    org.opencontainers.image.title="Open Data Grepper" \
    org.opencontainers.image.description="Grep Open Data without caching them locally" \
    org.opencontainers.image.version="v2.0" \
    org.opencontainers.image.source="https://github.com/andriibratanin/OpaGrepper" \
    org.opencontainers.image.authors="Andrii Bratanin"
#    org.opencontainers.image.revision="${COMMIT}" \

# Note: to find correct version of "libicu" library use:
# RUN ldconfig -p | grep -i icu || true
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libicu78 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR "/App"

COPY --from=builder publish/ .

ENV SOURCE_URL=""
ENV ICONV="true"
ENV RESULT_DIR="/Data"

VOLUME "/Data"

ENTRYPOINT ["./2_total"]
